export default [
  {
    user_id: 'user_1',
    user_name: 'john.smith_12123',
    user_custom: 'as d asdsada asdasdasda',
    email: 'john.smith@ya.ru',
    register_date: '2015-09-11T08:09:37+00:00',
    balance: 1350,
    wallet_amount: 0,
    wallet_currency: 'USD',
    enabled: true,
  },
  {
    user_id: 'test',
    user_name: null,
    user_custom: null,
    email: null,
    register_date: '2015-09-14T20:53:09+00:00',
    balance: 180,
    wallet_amount: 0,
    wallet_currency: null,
    enabled: true,
  },
  {
    user_id: 'a13xbaev',
    user_name: 'Alex',
    user_custom: 'Baev',
    email: 'a13xbaev@yandex.ru',
    register_date: '2015-09-14T21:03:32+00:00',
    balance: 1662,
    wallet_amount: 0,
    wallet_currency: 'USD',
    enabled: true,
  },
  {
    user_id: 'user_2',
    user_name: 'super mega user',
    user_custom: 'asd asda asd  asdasdasd',
    email: 'asdasdasdasd@asd.ru',
    register_date: '2015-09-15T15:05:25+00:00',
    balance: 104,
    wallet_amount: 0,
    wallet_currency: 'USD',
    enabled: true,
  },
  {
    user_id: 'user_3',
    user_name: 'rerer',
    user_custom: null,
    email: null,
    register_date: '2015-09-15T15:05:39+00:00',
    balance: 4,
    wallet_amount: 0,
    wallet_currency: null,
    enabled: false,
  },
  {
    user_id: 'user_4',
    user_name: 'eee',
    user_custom: 'tteesstt',
    email: null,
    register_date: '2015-09-15T15:14:54+00:00',
    balance: 0,
    wallet_amount: 0,
    wallet_currency: null,
    enabled: true,
  },
  {
    user_id: 'user_5',
    user_name: 'eee',
    user_custom: 'tteesstt',
    email: null,
    register_date: '2015-09-15T15:16:18+00:00',
    balance: 0,
    wallet_amount: 0,
    wallet_currency: null,
    enabled: true,
  },
  {
    user_id: 'user_6',
    user_name: null,
    user_custom: null,
    email: null,
    register_date: '2015-09-15T16:01:10+00:00',
    balance: 0,
    wallet_amount: 0,
    wallet_currency: null,
    enabled: true,
  },
  {
    user_id: 'RWJ',
    user_name: 'Ray',
    user_custom: 'William Ray',
    email: 'ray@asd.ru',
    register_date: '2015-09-15T16:08:24+00:00',
    balance: 132,
    wallet_amount: 0,
    wallet_currency: 'USD',
    enabled: true,
  },
  {
    user_id: 'wery weryyyyyyyyyyyyyyyy long name',
    user_name: '3434',
    user_custom: 'savdgh 5555',
    email: 'dfg@sdf.df',
    register_date: '2015-09-15T17:44:19+00:00',
    balance: -999999999999.9999,
    wallet_amount: 0,
    wallet_currency: 'USD',
    enabled: true,
  },
];
